#ifndef CONFIGURATION_TEST_LWIPOPTS_H
#define CONFIGURATION_TEST_LWIPOPTS_H

#define NO_SYS 1
#define LWIP_IPV4 1
#define LWIP_IPV6 0
#define LWIP_SOCKET 0
#define LWIP_NETCONN 0
#define LWIP_TIMERS 0
#define LWIP_STATS 0

#endif
